// Nationality_Area.m
// Power Query M: Nationality area lookup table + function
// Usage: paste into Power Query Advanced Editor and call fnNationalityArea("8826")

let
    NationalityAreaTable = Table.FromRecords({
        [code = "7826", label = "(02) Other"],
        [code = "000", label = "(03) UK"],
        [code = "2826", label = "(03) UK"],
        [code = "3826", label = "(03) UK"],
        [code = "5826", label = "(03) UK"],
        [code = "593", label = "(03) UK"],
        [code = "594", label = "(03) UK"],
        [code = "595", label = "(03) UK"],
        [code = "6826", label = "(03) UK"],
        [code = "999", label = "(03) UK"],
        [code = "4826", label = "(03) UK"],
        [code = "8826", label = "(04) Northern Ireland"],
        [code = "676", label = "(06) Ireland"],
        [code = "638", label = "(07) European Union (exc. EIRE) - Area 1"],
        [code = "653", label = "(07) European Union (exc. EIRE) - Area 1"],
        [code = "656", label = "(07) European Union (exc. EIRE) - Area 1"],
        [code = "661", label = "(07) European Union (exc. EIRE) - Area 1"],
        [code = "670", label = "(07) European Union (exc. EIRE) - Area 1"],
        [code = "727", label = "(07) European Union (exc. EIRE) - Area 1"],
        [code = "751", label = "(07) European Union (exc. EIRE) - Area 1"],
        [code = "849", label = "(07) European Union (exc. EIRE) - Area 1"],
        [code = "882", label = "(07) European Union (exc. EIRE) - Area 1"],
        [code = "883", label = "(07) European Union (exc. EIRE) - Area 1"],
        [code = "XE", label = "(07) European Union (exc. EIRE) - Area 1"],
        [code = "621", label = "(08) European Union (exc. EIRE) - Area 2"],
        [code = "700", label = "(08) European Union (exc. EIRE) - Area 2"],
        [code = "733", label = "(08) European Union (exc. EIRE) - Area 2"],
        [code = "831", label = "(08) European Union (exc. EIRE) - Area 2"],
        [code = "832", label = "(08) European Union (exc. EIRE) - Area 2"],
        [code = "833", label = "(08) European Union (exc. EIRE) - Area 2"],
        [code = "834", label = "(08) European Union (exc. EIRE) - Area 2"],
        [code = "835", label = "(08) European Union (exc. EIRE) - Area 2"],
        [code = "850", label = "(08) European Union (exc. EIRE) - Area 2"],
        [code = "610", label = "(09) European Union (exc. EIRE) - Area 3"],
        [code = "614", label = "(09) European Union (exc. EIRE) - Area 3"],
        [code = "641", label = "(09) European Union (exc. EIRE) - Area 3"],
        [code = "651", label = "(09) European Union (exc. EIRE) - Area 3"],
        [code = "678", label = "(09) European Union (exc. EIRE) - Area 3"],
        [code = "693", label = "(09) European Union (exc. EIRE) - Area 3"],
        [code = "710", label = "(09) European Union (exc. EIRE) - Area 3"],
        [code = "728", label = "(09) European Union (exc. EIRE) - Area 3"],
        [code = "755", label = "(09) European Union (exc. EIRE) - Area 3"],
        [code = "853", label = "(09) European Union (exc. EIRE) - Area 3"],
        [code = "878", label = "(09) European Union (exc. EIRE) - Area 3"],
        [code = "637", label = "(11) European Overseas Territories"],
        [code = "659", label = "(11) European Overseas Territories"],
        [code = "711", label = "(11) European Overseas Territories"],
        [code = "821", label = "(11) European Overseas Territories"],
        [code = "822", label = "(11) European Overseas Territories"],
        [code = "828", label = "(11) European Overseas Territories"],
        [code = "865", label = "(11) European Overseas Territories"],
        [code = "626", label = "(12) Overseas - Area 0"],
        [code = "771", label = "(12) Overseas - Area 0"],
        [code = "873", label = "(12) Overseas - Area 0"],
        [code = "612", label = "(13) Overseas - Area 1"],
        [code = "628", label = "(13) Overseas - Area 1"],
        [code = "631", label = "(13) Overseas - Area 1"],
        [code = "669", label = "(13) Overseas - Area 1"],
        [code = "672", label = "(13) Overseas - Area 1"],
        [code = "683", label = "(13) Overseas - Area 1"],
        [code = "684", label = "(13) Overseas - Area 1"],
        [code = "686", label = "(13) Overseas - Area 1"],
        [code = "698", label = "(13) Overseas - Area 1"],
        [code = "708", label = "(13) Overseas - Area 1"],
        [code = "717", label = "(13) Overseas - Area 1"],
        [code = "721", label = "(13) Overseas - Area 1"],
        [code = "731", label = "(13) Overseas - Area 1"],
        [code = "743", label = "(13) Overseas - Area 1"],
        [code = "746", label = "(13) Overseas - Area 1"],
        [code = "764", label = "(13) Overseas - Area 1"],
        [code = "766", label = "(13) Overseas - Area 1"],
        [code = "774", label = "(13) Overseas - Area 1"],
        [code = "779", label = "(13) Overseas - Area 1"],
        [code = "839", label = "(13) Overseas - Area 1"],
        [code = "652", label = "(14) Overseas - Area 2"],
        [code = "673", label = "(14) Overseas - Area 2"],
        [code = "681", label = "(14) Overseas - Area 2"],
        [code = "697", label = "(14) Overseas - Area 2"],
        [code = "718", label = "(14) Overseas - Area 2"],
        [code = "760", label = "(14) Overseas - Area 2"],
        [code = "772", label = "(14) Overseas - Area 2"],
        [code = "787", label = "(14) Overseas - Area 2"],
        [code = "842", label = "(14) Overseas - Area 2"],
        [code = "845", label = "(14) Overseas - Area 2"],
        [code = "1780", label = "(15) Overseas - Area 3"],
        [code = "601", label = "(15) Overseas - Area 3"],
        [code = "604", label = "(15) Overseas - Area 3"],
        [code = "609", label = "(15) Overseas - Area 3"],
        [code = "618", label = "(15) Overseas - Area 3"],
        [code = "620", label = "(15) Overseas - Area 3"],
        [code = "630", label = "(15) Overseas - Area 3"],
        [code = "658", label = "(15) Overseas - Area 3"],
        [code = "671", label = "(15) Overseas - Area 3"],
        [code = "677", label = "(15) Overseas - Area 3"],
        [code = "692", label = "(15) Overseas - Area 3"],
        [code = "694", label = "(15) Overseas - Area 3"],
        [code = "702", label = "(15) Overseas - Area 3"],
        [code = "703", label = "(15) Overseas - Area 3"],
        [code = "706", label = "(15) Overseas - Area 3"],
        [code = "714", label = "(15) Overseas - Area 3"],
        [code = "750", label = "(15) Overseas - Area 3"],
        [code = "756", label = "(15) Overseas - Area 3"],
        [code = "759", label = "(15) Overseas - Area 3"],
        [code = "765", label = "(15) Overseas - Area 3"],
        [code = "767", label = "(15) Overseas - Area 3"],
        [code = "768", label = "(15) Overseas - Area 3"],
        [code = "773", label = "(15) Overseas - Area 3"],
        [code = "780", label = "(15) Overseas - Area 3"],
        [code = "793", label = "(15) Overseas - Area 3"],
        [code = "825", label = "(15) Overseas - Area 3"],
        [code = "826", label = "(15) Overseas - Area 3"],
        [code = "827", label = "(15) Overseas - Area 3"],
        [code = "840", label = "(15) Overseas - Area 3"],
        [code = "841", label = "(15) Overseas - Area 3"],
        [code = "843", label = "(15) Overseas - Area 3"],
        [code = "844", label = "(15) Overseas - Area 3"],
        [code = "846", label = "(15) Overseas - Area 3"],
        [code = "847", label = "(15) Overseas - Area 3"],
        [code = "880", label = "(15) Overseas - Area 3"],
        [code = "881", label = "(15) Overseas - Area 3"],
        [code = "898", label = "(15) Overseas - Area 3"],
        [code = "997", label = "(15) Overseas - Area 3"],
        [code = "807", label = "(16) Overseas - Area 4"],
        [code = "602", label = "(16) Overseas - Area 4"],
        [code = "603", label = "(16) Overseas - Area 4"],
        [code = "605", label = "(16) Overseas - Area 4"],
        [code = "606", label = "(16) Overseas - Area 4"],
        [code = "607", label = "(16) Overseas - Area 4"],
        [code = "608", label = "(16) Overseas - Area 4"],
        [code = "611", label = "(16) Overseas - Area 4"],
        [code = "613", label = "(16) Overseas - Area 4"],
        [code = "616", label = "(16) Overseas - Area 4"],
        [code = "617", label = "(16) Overseas - Area 4"],
        [code = "619", label = "(16) Overseas - Area 4"],
        [code = "622", label = "(16) Overseas - Area 4"],
        [code = "623", label = "(16) Overseas - Area 4"],
        [code = "624", label = "(16) Overseas - Area 4"],
        [code = "625", label = "(16) Overseas - Area 4"],
        [code = "627", label = "(16) Overseas - Area 4"],
        [code = "629", label = "(16) Overseas - Area 4"],
        [code = "632", label = "(16) Overseas - Area 4"],
        [code = "633", label = "(16) Overseas - Area 4"],
        [code = "634", label = "(16) Overseas - Area 4"],
        [code = "635", label = "(16) Overseas - Area 4"],
        [code = "636", label = "(16) Overseas - Area 4"],
        [code = "640", label = "(16) Overseas - Area 4"],
        [code = "642", label = "(16) Overseas - Area 4"],
        [code = "643", label = "(16) Overseas - Area 4"],
        [code = "645", label = "(16) Overseas - Area 4"],
        [code = "646", label = "(16) Overseas - Area 4"],
        [code = "647", label = "(16) Overseas - Area 4"],
        [code = "648", label = "(16) Overseas - Area 4"],
        [code = "650", label = "(16) Overseas - Area 4"],
        [code = "654", label = "(16) Overseas - Area 4"],
        [code = "655", label = "(16) Overseas - Area 4"],
        [code = "660", label = "(16) Overseas - Area 4"],
        [code = "662", label = "(16) Overseas - Area 4"],
        [code = "663", label = "(16) Overseas - Area 4"],
        [code = "664", label = "(16) Overseas - Area 4"],
        [code = "665", label = "(16) Overseas - Area 4"],
        [code = "666", label = "(16) Overseas - Area 4"],
        [code = "667", label = "(16) Overseas - Area 4"],
        [code = "668", label = "(16) Overseas - Area 4"],
        [code = "674", label = "(16) Overseas - Area 4"],
        [code = "675", label = "(16) Overseas - Area 4"],
        [code = "679", label = "(16) Overseas - Area 4"],
        [code = "680", label = "(16) Overseas - Area 4"],
        [code = "682", label = "(16) Overseas - Area 4"],
        [code = "685", label = "(16) Overseas - Area 4"],
        [code = "687", label = "(16) Overseas - Area 4"],
        [code = "688", label = "(16) Overseas - Area 4"],
        [code = "689", label = "(16) Overseas - Area 4"],
        [code = "690", label = "(16) Overseas - Area 4"],
        [code = "691", label = "(16) Overseas - Area 4"],
        [code = "695", label = "(16) Overseas - Area 4"],
        [code = "696", label = "(16) Overseas - Area 4"],
        [code = "699", label = "(16) Overseas - Area 4"],
        [code = "701", label = "(16) Overseas - Area 4"],
        [code = "704", label = "(16) Overseas - Area 4"],
        [code = "707", label = "(16) Overseas - Area 4"],
        [code = "709", label = "(16) Overseas - Area 4"],
        [code = "712", label = "(16) Overseas - Area 4"],
        [code = "713", label = "(16) Overseas - Area 4"],
        [code = "715", label = "(16) Overseas - Area 4"],
        [code = "716", label = "(16) Overseas - Area 4"],
        [code = "722", label = "(16) Overseas - Area 4"],
        [code = "723", label = "(16) Overseas - Area 4"],
        [code = "724", label = "(16) Overseas - Area 4"],
        [code = "725", label = "(16) Overseas - Area 4"],
        [code = "726", label = "(16) Overseas - Area 4"],
        [code = "730", label = "(16) Overseas - Area 4"],
        [code = "732", label = "(16) Overseas - Area 4"],
        [code = "734", label = "(16) Overseas - Area 4"],
        [code = "736", label = "(16) Overseas - Area 4"],
        [code = "737", label = "(16) Overseas - Area 4"],
        [code = "738", label = "(16) Overseas - Area 4"],
        [code = "739", label = "(16) Overseas - Area 4"],
        [code = "741", label = "(16) Overseas - Area 4"],
        [code = "742", label = "(16) Overseas - Area 4"],
        [code = "744", label = "(16) Overseas - Area 4"],
        [code = "745", label = "(16) Overseas - Area 4"],
        [code = "747", label = "(16) Overseas - Area 4"],
        [code = "748", label = "(16) Overseas - Area 4"],
        [code = "749", label = "(16) Overseas - Area 4"],
        [code = "752", label = "(16) Overseas - Area 4"],
        [code = "753", label = "(16) Overseas - Area 4"],
        [code = "754", label = "(16) Overseas - Area 4"],
        [code = "757", label = "(16) Overseas - Area 4"],
        [code = "761", label = "(16) Overseas - Area 4"],
        [code = "762", label = "(16) Overseas - Area 4"],
        [code = "763", label = "(16) Overseas - Area 4"],
        [code = "769", label = "(16) Overseas - Area 4"],
        [code = "770", label = "(16) Overseas - Area 4"],
        [code = "775", label = "(16) Overseas - Area 4"],
        [code = "777", label = "(16) Overseas - Area 4"],
        [code = "778", label = "(16) Overseas - Area 4"],
        [code = "781", label = "(16) Overseas - Area 4"],
        [code = "782", label = "(16) Overseas - Area 4"],
        [code = "783", label = "(16) Overseas - Area 4"],
        [code = "784", label = "(16) Overseas - Area 4"],
        [code = "785", label = "(16) Overseas - Area 4"],
        [code = "786", label = "(16) Overseas - Area 4"],
        [code = "788", label = "(16) Overseas - Area 4"],
        [code = "789", label = "(16) Overseas - Area 4"],
        [code = "790", label = "(16) Overseas - Area 4"],
        [code = "791", label = "(16) Overseas - Area 4"],
        [code = "792", label = "(16) Overseas - Area 4"],
        [code = "794", label = "(16) Overseas - Area 4"],
        [code = "795", label = "(16) Overseas - Area 4"],
        [code = "796", label = "(16) Overseas - Area 4"],
        [code = "797", label = "(16) Overseas - Area 4"],
        [code = "798", label = "(16) Overseas - Area 4"],
        [code = "800", label = "(16) Overseas - Area 4"],
        [code = "802", label = "(16) Overseas - Area 4"],
        [code = "803", label = "(16) Overseas - Area 4"],
        [code = "804", label = "(16) Overseas - Area 4"],
        [code = "805", label = "(16) Overseas - Area 4"],
        [code = "836", label = "(16) Overseas - Area 4"],
        [code = "837", label = "(16) Overseas - Area 4"],
        [code = "838", label = "(16) Overseas - Area 4"],
        [code = "848", label = "(16) Overseas - Area 4"],
        [code = "851", label = "(16) Overseas - Area 4"],
        [code = "852", label = "(16) Overseas - Area 4"],
        [code = "854", label = "(16) Overseas - Area 4"],
        [code = "860", label = "(16) Overseas - Area 4"],
        [code = "861", label = "(16) Overseas - Area 4"],
        [code = "862", label = "(16) Overseas - Area 4"],
        [code = "863", label = "(16) Overseas - Area 4"],
        [code = "864", label = "(16) Overseas - Area 4"],
        [code = "870", label = "(16) Overseas - Area 4"],
        [code = "874", label = "(16) Overseas - Area 4"],
        [code = "884", label = "(16) Overseas - Area 4"],
        [code = "998", label = "(16) Overseas - Area 4"],
        [code = "XN", label = "(16) Overseas - Area 4"],
        [code = "615", label = "(17) British Overseas Territories"],
        [code = "649", label = "(17) British Overseas Territories"],
        [code = "705", label = "(17) British Overseas Territories"],
        [code = "735", label = "(17) British Overseas Territories"],
        [code = "776", label = "(17) British Overseas Territories"],
        [code = "799", label = "(17) British Overseas Territories"],
        [code = "801", label = "(17) British Overseas Territories"],
        [code = "823", label = "(17) British Overseas Territories"],
        [code = "824", label = "(17) British Overseas Territories"],
        [code = "829", label = "(17) British Overseas Territories"],
        [code = "830", label = "(17) British Overseas Territories"]
    }),
    
    fnNationalityArea = (code as nullable text) as nullable text =>
        let
            input = if code = null then null else Text.Trim(Text.Upper(code)),
            found = if input = null then null else Table.SelectRows(NationalityAreaTable, each Text.Upper(Text.From([code])) = input),
            result = if input = null then null else if Table.RowCount(found) = 0 then null else Record.Field(Table.First(found), "label")
        in
            result

in
    [ NationalityAreaTable = NationalityAreaTable, fnNationalityArea = fnNationalityArea ]